CREATE TABLE `stums`.`volunteer` (
  `PID` INT NOT NULL AUTO_INCREMENT,
  `SID` VARCHAR(20) NOT NULL,
  `idx` INT NULL,
  `title` VARCHAR(50) NULL,
  `organization` VARCHAR(50) NULL,
  `type` INT NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  `duration` VARCHAR(30) NULL,
  `link_name` VARCHAR(45) NULL,
  `link` VARCHAR(50) NULL,
  `remarks` TEXT NULL,
  `status_one` INT NULL,
  `status_two` INT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`PID`));

CREATE TABLE `stums`.`socialwork` (
  `PID` INT NOT NULL AUTO_INCREMENT,
  `SID` VARCHAR(20) NOT NULL,
  `idx` INT NULL,
  `score` FLOAT NULL,
  `title` VARCHAR(50) NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  `link_name` VARCHAR(45) NULL,
  `link` VARCHAR(50) NULL,
  `remarks` TEXT NULL,
  `status_one` INT NULL,
  `status_two` INT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`PID`));

CREATE TABLE `stums`.`competition` (
  `PID` INT NOT NULL AUTO_INCREMENT,
  `SID` VARCHAR(20) NOT NULL,
  `idx` INT NULL,
  `score` FLOAT NULL,
  `type` INT NULL,
  `name` VARCHAR(45) NULL,
  `organization` VARCHAR(50) NULL,
  `date` DATE NULL,
  `title` VARCHAR(50) NULL,
  `level` INT NULL,
  `rank` INT NULL,
  `team` TEXT NULL,
  `link_name` VARCHAR(45) NULL,
  `link` VARCHAR(50) NULL,
  `remarks` TEXT NULL,
  `status_one` INT NULL,
  `status_two` INT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`PID`));

CREATE TABLE `stums`.`paper` (
  `PID` INT NOT NULL AUTO_INCREMENT,
  `SID` VARCHAR(20) NOT NULL,
  `idx` INT NULL,
  `score` FLOAT NULL,
  `title` VARCHAR(50) NULL,
  `type` INT NULL,
  `publish` VARCHAR(50) NULL,
  `author_level` INT NULL,
  `authors` TEXT NULL,
  `corresponding_author` VARCHAR(45) NULL,
  `ISSN_CN` VARCHAR(45) NULL,
  `factor` FLOAT NULL,
  `published_status` INT NULL,
  `submission_date` DATE NULL,
  `received_date` DATE NULL,
  `publication_date` DATE NULL,
  `range` VARCHAR(45) NULL,
  `DOI_PMID` VARCHAR(45) NULL,
  `CCF` VARCHAR(45) NULL,
  `partition` INT NULL,
  `inclusion` INT NULL,
  `publisher` VARCHAR(50) NULL,
  `language` VARCHAR(20) NULL,
  `award_flag` INT NULL,
  `collaborative_one` INT NULL,
  `collaborative_two` INT NULL,
  `link_name` VARCHAR(45) NULL,
  `link` VARCHAR(50) NULL,
  `remarks` TEXT NULL,
  `status_one` INT NULL,
  `status_two` INT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`PID`));

CREATE TABLE `stums`.`patent` (
  `PID` INT NOT NULL AUTO_INCREMENT,
  `SID` VARCHAR(20) NOT NULL,
  `idx` INT NULL,
  `score` FLOAT NULL,
  `title` VARCHAR(50) NULL,
  `type` INT NULL,
  `application_num` VARCHAR(50) NULL,
  `certificate_num` VARCHAR(50) NULL,
  `team` TEXT NULL,
  `acceptance` INT NULL,
  `acceptance_date` DATE NULL,
  `release` INT NULL,
  `release_date` DATE NULL,
  `empower` INT NULL,
  `empower_date` DATE NULL,
  `transferred` INT NULL,
  `transferred_date` DATE NULL,
  `link_name` VARCHAR(45) NULL,
  `link` VARCHAR(50) NULL,
  `remarks` TEXT NULL,
  `status_one` INT NULL,
  `status_two` INT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`PID`));

CREATE TABLE `stums`.`copyright` (
  `PID` INT NOT NULL AUTO_INCREMENT,
  `SID` VARCHAR(20) NOT NULL,
  `idx` INT NULL,
  `score` FLOAT NULL,
  `title` VARCHAR(50) NULL,
  `author_level` INT NULL,
  `team` TEXT NULL,
  `application_status` INT NULL,
  `date` DATE NULL,
  `link_name` VARCHAR(45) NULL,
  `link` VARCHAR(50) NULL,
  `remarks` TEXT NULL,
  `status_one` INT NULL,
  `status_two` INT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`PID`));

CREATE TABLE `stums`.`publication` (
  `PID` INT NOT NULL AUTO_INCREMENT,
  `SID` VARCHAR(20) NOT NULL,
  `idx` INT NULL,
  `score` FLOAT NULL,
  `title` VARCHAR(50) NULL,
  `author_level` INT NULL,
  `team` TEXT NULL,
  `publisher` VARCHAR(50) NULL,
  `type` TEXT NULL,
  `date` DATE NULL,
  `ISBN` VARCHAR(50) NULL,
  `link_name` VARCHAR(45) NULL,
  `link` VARCHAR(50) NULL,
  `remarks` TEXT NULL,
  `status_one` INT NULL,
  `status_two` INT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`PID`));

CREATE TABLE `stums`.`exchange` (
  `PID` INT NOT NULL AUTO_INCREMENT,
  `SID` VARCHAR(20) NOT NULL,
  `title` VARCHAR(50) NULL,
  `type` INT NULL,
  `funding_source` VARCHAR(50) NULL,
  `country` VARCHAR(30) NULL,
  `city` VARCHAR(30) NULL,
  `institution` VARCHAR(45) NULL,
  `duration` INT NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  `current_status` INT NULL,
  `flag1` INT NULL,
  `flag2` INT NULL,
  `flag3` INT NULL,
  `flag4` INT NULL,
  `link_name` VARCHAR(45) NULL,
  `link` VARCHAR(50) NULL,
  `remarks` TEXT NULL,
  `status_one` INT NULL,
  `status_two` INT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`PID`));