server:
  port: 80

spring:
  application:
    name: gateway-service
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:dev}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 表明gateway开启服务注册和发现的功能，动态路由
          lowerCaseServiceId: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/**

        - id: score-service
          uri: lb://score-service
          predicates:
            - Path=/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/**
