eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: jt123456
    driver-class-name: com.mysql.cj.jdbc.Driver