version: '2.2'
services:
  gateway-service:
    build: ../gateway-service
    container_name: stums-gateway-service
    restart: always
    ports:
      - "80:80"

  auth-service:
    build: ../auth-service
    container_name: stums-auth-service
    restart: always
    ports:
      - "1005:1005"
    depends_on:
      - gateway-service

  user-service:
    build: ../user-service
    container_name: stums-user-service
    restart: always
    ports:
      - "1001:1001"
    depends_on:
      - gateway-service

  score-service:
    build: ../score-service
    container_name: stums-score-service
    restart: always
    ports:
      - "1002:1002"
    depends_on:
      - gateway-service



