version: '2.2'
services:
  eureka:
    build: ../eureka
    container_name: eureka
    restart: always
    entrypoint: java -jar /eureka.jar
    ports:
      - "8761:8761"

  user-service:
    build: ../user-service
    container_name: user-service
    restart: always
    ports:
      - "1001:1001"
    entrypoint: java -jar /user-service.jar
    depends_on:
      - eureka

  score-service:
    build: ../score-service
    container_name: score-service
    restart: always
    ports:
      - "1002:1002"
    entrypoint: java -jar /score-service.jar
    depends_on:
      - eureka
      - user-service

  gateway-service:
    build: ../gateway-service
    container_name: gateway-service
    restart: always
    ports:
      - "80:80"
    entrypoint: java -jar /gateway-service.jar
    depends_on:
      - eureka
      - user-service
      - score-service


