eureka:
  instance:
    hostname: eureka

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver