server:
  port: 8080

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    # 禁用注册中心自己的注册行为
    registerWithEureka: false
    # 注册中心只需维护服务实例，不需检索服务，设 false
    fetchRegistry: false
    # 注册中心的服务访问地址，EL 表达式获取到上面的主机和端口号（注意： yml 配置文件是有顺序的）
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka
