server:
  port: 1001

spring:
  application:
    name: user-service
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:dev}

swagger:
  title: "user-service"
  description: "用户接口"
  version: V1.0
  enabled: true

jwt:
  tokenHeader: Authorization  # JWT存储的请求头
  secret: mall-admin-secret   # JWT加解密使用的密钥
  expiration: 604800          # JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '        # JWT负载中拿到开头



