eureka:
  instance:
    hostname: user-service

  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://1.12.37.226:3307/stums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver